# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/Sec-Dojo-Cyber-House/cve-hunters"

[social.params]
icon = "brand-github"

[[social]]
identifier = "discord"
name = "Discord"
url = "https://discord.gg/VVahUjRnuM"

[social.params]
icon = "brand-discord"

[[social]]
identifier = "email"
name = "Email"
url = "mailto:contact@cvehunters.com"

[social.params]
icon = "mail"

[[social]]
identifier = "linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/company/cve-hunters/"

[social.params]
icon = "brand-linkedin"