# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/Sec-Dojo-Cyber-House/cve-hunters"

[social.params]
icon = "brand-github"

[[social]]
identifier = "discord"
name = "Discord"
url = "https://discord.gg/xqXHJGan"

[social.params]
icon = "brand-discord"

[[social]]
identifier = "gmail"
name = "Gmail"
url = "mailto:secdojocyberhouse@gmail.com"

[social.params]
icon = "mail"